### PR TITLE
Added option for JSON output

### PR DESCRIPTION
**Pull request by martinbrose**
## Description

Added the option to get JSON output from the tool. 
To prepare for adding this to a Prometheus exporter and potentially adding upload speeds as well.

## Status

**READY**

## Related Issues

- No related issues

### CODE REVIEW

**Comment by n8henrie** [comment]
Hi -- thanks for your contribution!

I would consider merging this if you were _adding_ the ability to output as JSON, but with a quick look, it seems like you're _replacing_ the current functionality, which I'd rather not merge.

A much easier approach would be to just use the `--json` flag to format the output (instead of changing the function name and everything).

Also, I think you can just use "typing.Bool" (or something like that) from the stdlib.

Would you consider reverting those changes and taking this approach instead?

**Comment by martinbrose** [comment]
Hi Nathan,

thanks for your detailed reply.
Makes sense, I'll change it this week and will update the PR by next weekend.

**Comment by martinbrose** [comment]
I have now performed the following:
- Changed back to the original function names etc. I think originally I wanted to put too many changes into the PR. Some functions might only need to be changed once additional functionality is added, like upload speed tests;
- Now using the normal bool from the stdlib;
- The option --json outputs the download speed, basically only reformatting the normal print output;
- In combination with --verbose, the --json outputs the response json of the request for targets;
- I removed the `if v` from the `args = {k: v for k, v in vars(namespace).items() if v}`, so I can use if / else for the output, without error catching;
- Also had to change the `verbosity` to `verbose` in the call of `main(timeout=timeout, verbosity=verbose)` because otherwise I receive the following error message: `TypeError: run() got an unexpected keyword argument 'verbose'`. So this might need to be addressed in another update if you don't merge this PR.

Hope this makes sense.

**Comment by n8henrie** [comment]
It looks like there's a modest amount of duplicated changes in these two PRs -- I think the pattern generally would be to:
- start at the `dev` branch
- create a branch for your PR: `git checkout -b branch_name`
- make and commit your changes
- submit your pr
- **then reset back to the `dev` branch**
- rinse and repeat for the next PR

I could then merge one PR, then rebase the second PR on the new `dev`, then merge both into `master` once ready.

**Comment by n8henrie** [comment]
I haven't gotten a reply, so I'm closing this as dead. Please feel free to let me know if I should re-open.

**Pull request closed without merging**
