### PR TITLE
Add byte ranges to the request urls

### PR DESCRIPTION
**Pull request by martinbrose**
## Description

Added client information and added option to define byte ranges in the request urls.
Also made the code a bit more modular to have the flexibility for the upcoming upload tests.

## Status

**READY**

## Related Issues

- No related issue

### CODE REVIEW

**Comment by n8henrie** [comment]
Thanks for contributing!

What is the `numbytes` argument for? Do you know what the default is? If you manually select a very high or low value, what happens?

Would you mind hiding the extra output behind a `--verbose` flag? These are often done in argparse as an accumulator (`-v` vs `-vvv`) that translates to a logging level, though this approach would output to stderr instead of stdout I think.

**Comment by martinbrose** [comment]
Hi, thanks for your replies to my pull requests!

I'm using `numbytes` in the calls to the speed test to define the request / payload size.
Fast.com seems to be using the following:
- 0 for latency test, 
- 2048 and 26214400 (and a little smaller) for the download tests , and
- 26214400 for the upload tests.

So the maximum payload for fast.com seems to be 26214400.

I suspect that this will help us with the implementation of upload speeds too.

In regards to the extra output, I was thinking about adding this to the json output (if you accept the other pull request). But putting this additionally into the `--verbose` is a good idea. Will look into it.

**Comment by martinbrose** [comment]
I have moved the option of client info output to pull request #6.

So this pull request can just focus on adding the `numbytes` to the requests.

**Comment by martinbrose** [comment]
Just looking at the option to define the size of the payload... it might not make much sense to add this at the moment.

I might just close this PR and include it in another feature request PR for adding latency tests or upload tests.
I have too much refactoring going on in this PR anyway. All in prep to have the latency test or upload test option.

**Pull request closed without merging**
